### PR TITLE
Add redirects for paygap.pif.gov and tophealth.pif.gov

### PR DESCRIPTION
**Pull request by svenaas**
Redirect paygap.pif.gov and tophealth.pif.gov to pif.gov

### CODE REVIEW

**Review by davemcorwin — CHANGES_REQUESTED** [review]
I think there are required additions in the docker-compose.yml file as well, maybe the readme needs to be updated with this well? It might be covered in a different section.

**Comment by svenaas** [comment]
I may have just missed it. Gimme a sec.

**Review by apburnes — APPROVED** [review]

**Comment by svenaas** [comment]
@davemcorwin it's blocking my merge because of your requested change, which I think I took care of. Could you take another look?

**Comment by svenaas** [comment]
(I'm sure I can merge anyway, but wanted you to have a chance to see it first.)

**Review by davemcorwin — APPROVED** [review]

**Pull request merged**
