### PR TITLE
Adding redirect for the Partnership Principles

### PR DESCRIPTION
**Pull request by elainekamlley**
Redirect from `partnership-playbook.18f.gov` to `18f.gsa.gov/partnership-principles`

### CODE REVIEW

**Comment by jseppi** [comment]
This will only redirect `pages.18f.gov/partnership-playbook` -> `www.18f.gsa.gov/partnership-principles`.

The `partnership-playbook.18f.gov` -> `www.18f.gsa.gov/partnership-principles` redirect would have to be done elsewhere if it is needed.

Also are you sure you want the `www` there? https://www.18f.gsa.gov/partnership-principles doesn't seem to work, but https://18f.gsa.gov/partnership-principles does.

**Comment by elainekamlley** [comment]
@jseppi thanks for that catch. I can take off that `www`. Do I need to add `https`?

As for the `partnership-playbook.18f.gov` @wslack do you know who owns that?

**Comment by jseppi** [comment]
Nope, you don't need the `https`

**Comment by wslack** [comment]
@elainekamlley let's chat. This redirect tool won't help you with the current issue - you should check how Aaron set up https://github.com/18f/open-foia-redirect/

**Comment by wslack** [comment]
@elainekamlley we can now circle back to doing this in this app!

**Pull request closed without merging**
