### PR TITLE
Switch to using CircleCI in place of Travis

### PR DESCRIPTION
**Pull request by jseppi**
This PR switches the project from using TravisCI to CircleCI, which is now the only approved continuous integration service we can can use.

After review, but before merging:
- [x] Add the project to CircleCI: https://circleci.com/dashboard
- [x] Add CircleCI and remove TravisCI from required merge to `master` checks: https://github.com/18F/pages-redirects/settings/branches/master
- [x] Create new production deployer account credentials and save them as `CF_USER` and `CF_PASS` in CircleCI's configuration panel: https://circleci.com/gh/18F/pages-redirects/edit#env-vars

After merge and confirmation that it all works:
- [ ] Remove project from Travis (if that even needs to be done)
- [ ] Delete cloud.gov deployer service account that was used in Travis

### CODE REVIEW

**Comment by jseppi** [comment]
Ready for review, @jmhooper.

**Comment by jseppi** [comment]
@wslack deployer service creation issue has been resolved, so I should be able to finish this up in a short amount of time once I get back on it, probably this afternoon. Would that work for you?

**Comment by wslack** [comment]
I'm OOO this afternoon.

**Comment by jseppi** [comment]
Tests already run properly. 

The only risk is that the deployment fails, but I tested it (non production) and don't anticipate any problems there. If it does fail, the existing deployment will still be up (because of using `cf-autopilot`), so there will not be any downtime. If it does bomb, we can just revert quickly back to Travis.

**Comment by wslack** [comment]
Ok, and inflight PR's won't be affected? If so, we're good to implement as long as there's an easy rollback plan.

**Comment by jseppi** [comment]
Bleh, it might be a pain because they'll need to pull in the changes from this PR after it is merged.

There's no rush in getting this switched over, so I'm fine with waiting until existing PRs are done.

**Comment by wslack** [comment]
@jseppi this is ready when you are ready! go ahead?

**Pull request merged**
