### PR TITLE
Redirect identity-dev-docs to developers.login.gov

### PR DESCRIPTION
**Pull request by zachmargolis**

### CODE REVIEW

**Comment by zachmargolis** [comment]
Just realized this is duplicated by #71, which only uses nginx, not the YAML like in the README. Which is the right way to go?

**Comment by wslack** [comment]
@zachmargolis this is the right PR. I haven't had occasion to apply the new domain instructions before and forgot about them. (READMEs, they're great)

**Comment by zachmargolis** [comment]
@wslack thanks! Updated the tests to check for `toDomain`, PTAL!

**Comment by wslack** [comment]
Flagging this PR for another Federalist reviewer to 👍

**Comment by zachmargolis** [comment]
Ok thanks! Looks like I can't merge, but thanks for the review!

**Pull request merged**
